version: '3.7'
services:
  flask-app:
    image: flaskproject:latest
    build: .
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      FLASKPROJECTDBURI: ${FLASK_PROJECT_DB_URI}
      SECRETKEY: ${SECRET_KEY}
  